language: java
jdk:
  - oraclejdk7
env:
  - DITA_DIR=DITA-OT1.8.5 ANT_OPTS=-Xmx512m $ANT_OPTS -Djavax.xml.transform.TransformerFactory=net.sf.saxon.TransformerFactoryImpl CLASSPATH=DITA-OT1.8.5/lib/dost.jar:DITA-OT1.8.5/lib/commons-codec-1.4.jar:DITA-OT1.8.5/lib/resolver.jar:lib/icu4j.jar:DITA-OT1.8.5/lib/xercesImpl.jar:DITA-OT1.8.5/lib/xml-apis.jar:DITA-OT1.8.5/lib/saxon/saxon9.jar:DITA-OT1.8.5/lib/saxon/saxon9-dom.jar
before_script:
  - chmod +x travis-before-install.sh
  - chmod +x run-tests.sh
  - ./travis-before-script.sh
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - ./travis-before-install.sh
script: "./run-tests.sh"
# Handle git submodules yourself
git:
    submodules: false
